theme: jekyll-theme-minimal
title: Glassful Enterprises Inc.
logo: /assets/img/glassful.png
description: Stealth social consumption startup
show_downloads: false
google_analytics: 

social:
  name: Glassful Enterprises, Inc.
  links:

